#coding=utf-8
#Version: V 1.0
author: 'WangSheng'
date: '2018/12/5 17:11'

#opc api url地址
OPC_REAL_DATA_API= 'http://10.60.124.143:1229/api/list'
OPC_DATA_CLASSIFICATION_GRQ = 'GRQ'
OPC_DATA_CLASSIFICATION_HQ = 'HQ'
OPC_DATA_CLASSIFICATION_OHTER = 'OHTER'
OPC_DATA_CLASSIFICATION_QQ = 'QQ'
OPC_DATA_CLASSIFICATION_ZRQ = 'ZRQ'
OPC_DATA_CLASSIFICATION_BSGR = 'BSGR'
OPC_DATA_CLASSIFICATION_DLGR = 'DLGR'